### ISSUE TITLE
Can't install msumastro 0.8.2 in anaconda, neither with "conda" nor with "pip"

### ISSUE THREAD

**Issue by hgeagle** [mwcraig/msumastro#209]
, both install only older version.
E.g., I tried to install per your instructions:
conda install -c http://conda.anaconda.org/mwcraig msumastro

**Comment by mwcraig** [comment]
@hgeagle -- sorry about that, having been keeping the conda package up to date. What platform are you on?

I am able to install with pip, though I get the latest version, which is 0.8.5. Is there a reason you need 0.8.2 specifically?

**Comment by hgeagle** [comment]
Hello Matt,

No, I do not need 0.8.2 specifically (this shows up in the anaconda table,
I believe), the newest version would hopefully suffice  :)
There seems to be some confusion regarding ipython and jupyter notebooks,
which might make the proper installation of the "right" package
necessary(?).

Cheers,
Helmar

**Comment by mwcraig** [comment]
Hi Helmar,

Are you getting an error when you try `pip install msumastro`? If you could paste in a copy of any error msgs you are getting that would be great!

Matt

**Comment by mwcraig** [comment]
Closing (assuming the underlying issue has gone away).
